export { ManifestCollector } from './collector.js'
export type { CollectorOptions, RecordInput } from './collector.js'
export { createBabelPlugin, resolveComponentName } from './babel-plugin.js'
export type { BabelTypes, ProvenanceBabelOptions } from './babel-plugin.js'
export { createProvenance } from './vite-plugin.js'
export type { ProvenanceBundle, ProvenanceViteOptions, VitePluginLike } from './vite-plugin.js'
